[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bluescrypto_staking = "GWNpsKtdNy9LEZ4P86VHXGB8d25voFYKQDyvVNMixPcP"
bluescoin = "FQ8uvnRBAMkbxHxZPboh2p5fgYnH4tBDFKSNbYjPY6ne"

[programs.devnet]
bluescrypto_staking = "GWNpsKtdNy9LEZ4P86VHXGB8d25voFYKQDyvVNMixPcP"
bluescoin = "FQ8uvnRBAMkbxHxZPboh2p5fgYnH4tBDFKSNbYjPY6ne"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/leon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test.ts"
